---
- name: Install NginX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:

    - name: Install gnupg2
      apt:
        name: gnupg2
        update_cache: yes
      tags:
        - gnupg-package
        - packages

    - name: Add key from nginx repository
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
      tags:
        - nginx-signkey

    - name: Add nginx repository
      apt_repository:
        repo: deb https://nginx.org/packages/mainline/debian/ bullseye nginx
        state: present

    - name: Install NginX
      apt:
        name: nginx
        update_cache: yes
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: Create NginX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

